name: Update GitHub Stats Images

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Stats SVG
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=jafarm83&show_icons=true&theme=radical&hide_border=true&v=$(date +%s)"
          curl -o top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=jafarm83&layout=compact&theme=radical&hide_border=true&v=$(date +%s)"

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg top-langs.svg
          git diff --staged --quiet || git commit -m "Auto-update GitHub stats images [skip ci]"
          git push
